In [3]:
from skimage import color
from skimage import io

import matplotlib.pyplot as plt
%matplotlib inline

import matplotlib.image as mpimg
# import image

import numpy as np
import cv2

from PIL import Image


import sys
import numpy as np
import skimage.color
import skimage.io
from matplotlib import pyplot as plt


In [4]:
class Assignment_02:
    
    def __init__(self,user_input_image):
#         self.user_input_image = image
#        
        pass
    def to_grey_scale(self,img_path):
        
#         image  =  plt.imread("Datasets/ramdom1.jpg")
#         image = skimage.io.imread(img_path, as_gray=True)
        
        # pre processing the image to convert the into grayscale
        image = cv2.imread(img_path)
        image = cv2.cvtColor(src=image, code=cv2.COLOR_BGR2GRAY)
        return image
    
    

    # display the image
#         skimage.io.imshow(image)
# 
        
    def display_image(self,image,title = "Not available"):
        
#         print(image.size)
#         skimage.io.imshow(image)
        plt.imshow(image)
        plt.title(title)
        plt.show()
        
    
    
    
    
    
    def convolve2D(self,image, kernel, padding=0, strides=1):
        # Cross Correlation
        kernel = np.flipud(np.fliplr(kernel))

        # Gather Shapes of Kernel + Image + Padding
        xKernShape = kernel.shape[0]
        yKernShape = kernel.shape[1]
        xImgShape = image.shape[0]
        yImgShape = image.shape[1]

        # Shape of Output Convolution
        xOutput = int(((xImgShape - xKernShape + 2 * padding) / strides) + 1)
        yOutput = int(((yImgShape - yKernShape + 2 * padding) / strides) + 1)
        output = np.zeros((xOutput, yOutput))

        # Apply Equal Padding to All Sides
        if padding != 0:
            imagePadded = np.zeros((image.shape[0] + padding*2, image.shape[1] + padding*2))
            imagePadded[int(padding):int(-1 * padding), int(padding):int(-1 * padding)] = image
            print(imagePadded)
        else:
            imagePadded = image

        # Iterate through image
        for y in range(image.shape[1]):
            # Exit Convolution
            if y > image.shape[1] - yKernShape:
                break
            # Only Convolve if y has gone down by the specified Strides
            if y % strides == 0:
                for x in range(image.shape[0]):
                    # Go to next row once kernel is out of bounds
                    if x > image.shape[0] - xKernShape:
                        break
                    try:
                        # Only Convolve if x has moved by the specified Strides
                        if x % strides == 0:
                            output[x, y] = (kernel * imagePadded[x: x + xKernShape, y: y + yKernShape]).sum()
                    except:
                        break

        return output        


    def Question_1(self,grayscale_image,kernal):
        '''
        Question 1 will give you the effect of Sobel operator on the give image
        parameters : 
            its take two parameters . first parameter take the grayscale image adn 2nd 
            parameter take the kernal(filter of sobel operator)
        '''
        image = self.convolve2D(grayscale_image,kernal,padding=2)
        cv2.imwrite('Question_1_sobel_operator.png',image)

    def Question_2(self,grayscale_image,axis=0, ddof=0):
        ''' Question_2() will return you singal to the noise ratio of the image
        
        parameters : 
        it take only one parameter which is 2D image
        
        '''
        one_D_array = np.asarray(grayscale_image)
        mean = one_D_array.mean(axis)
        std = one_D_array.std(axis=axis,ddof=ddof)
        
        return  np.where(std == 0, 0, mean/std)
    
    def Question_4(self,image_path):
        '''
        Queston_4() has only one paramter and it will convert the image into the
                    frequncy domain and display the spectrum and and phase angle (Theta)
            parameters : 
                it takes only one paramter which is path of the image.
        '''
        img = cv2.imread(image_path,0)
        f = np.fft.fft2(img)
        fshift = np.fft.fftshift(f)
        magnitude_spectrum = 20*np.log(np.abs(fshift))
        plt.subplot(121)
        plt.imshow(img, cmap = 'gray')
        plt.title('Input Image')
        plt.xticks([]), plt.yticks([])
        plt.subplot(122)
        plt.imshow(magnitude_spectrum, cmap = 'gray')
        plt.title('Magnitude Spectrum'), plt.xticks([]), plt.yticks([])
        plt.show()
        
    def Question_5(self,image_path):
        '''
            Question_5() is actually high pass filter.
            parameters : 
                it takes only one parameter which is image path
                
        '''
        img = cv2.imread(image_path,0)
        f = np.fft.fft2(img)
        F2 = np.fft.fftshift(f)
        magnitude_spectrum = 20*np.log(np.abs(F2))

        (w, h) = img.shape
        half_w, half_h = int(w/2), int(h/2)

        # high pass filter
        n = 25
        F2[half_w-n:half_w+n+1,half_h-n:half_h+n+1] = 0 # select all but the first 50x50 (low) frequencies
        plt.figure(figsize=(10,10))
        plt.imshow( (20*np.log10( 0.1 + F2)).astype(int))
        plt.show()
    
    def Question_6(self,image_path):
        '''
            Question_6 is actually low pass filter it block the low pass frequncy:
            paramter : 
                it takes only parmeter which is image path
        '''
        img = cv2.imread(image_path,0)
        f = np.fft.fft2(img)
        F2 = np.fft.fftshift(f)
        magnitude_spectrum = 20*np.log(np.abs(F2))

        (w, h) = img.shape
        half_w, half_h = int(w/2), int(h/2)

        im1 = fp.ifft2(fftpack.ifftshift(F2)).real
        plt.figure(figsize=(10,10))
        plt.imshow(im1, cmap='gray')
        plt.axis('off')
        plt.show()

if __name__ == '__main__':
    
    image_path = "Datasets/1.png"
    a02 = Assignment_02(image_path)
#     a02.display_image(orignal_image , "Orignal image")
    
    
    grayscale_image = a02.to_grey_scale(image_path)
#
    a02.display_image(grayscale_image , "Grayscale image")
    
    kernal = np.array([
            [1,0,-1],
            [1,0,-1],
            [1,0,-1]
    ])
#     kernel = np.ones((5,5),np.float32)/25

#     a02.Question_1(grayscale_image,kernal)
#     a02.Question_2(grayscale_image)
#     a02.Question_4(image_path)
#     a02.Question_5(image_path)
    a02.Question_6(image_path)
    
    
    

[ WARN:0@2.921] global /io/opencv/modules/imgcodecs/src/loadsave.cpp (239) findDecoder imread_('Datasets/1.png'): can't open/read file: check file path/integrity


error: OpenCV(4.5.5) /io/opencv/modules/imgproc/src/color.cpp:182: error: (-215:Assertion failed) !_src.empty() in function 'cvtColor'


In [41]:
def processImage(image):
    image = cv2.imread(image)
    image = cv2.cvtColor(src=image, code=cv2.COLOR_BGR2GRAY)
    return image

grayscale_image = processImage("Datasets/1.png")


    
if __name__ == '__main__':
    
    image = processImage("Datasets/ramdom1.jpg")
    print(image)
    kernel = np.array([
        [1, 0, -1], 
        [1, 0, -1], 
        [1, 0, -1]])
    
    output = convolve2D(image ,kernel,padding=2)
    cv2.imwrite('2Dconvulution_02.png',output)
    

[[212 212 211 ... 254 254 254]
 [211 211 209 ... 255 255 255]
 [212 212 211 ... 254 254 254]
 ...
 [140 140 143 ... 193 193 192]
 [133 133 136 ... 193 193 193]
 [135 134 134 ... 190 191 192]]
[[  0.   0.   0. ...   0.   0.   0.]
 [  0.   0.   0. ...   0.   0.   0.]
 [  0.   0. 212. ... 254.   0.   0.]
 ...
 [  0.   0. 135. ... 192.   0.   0.]
 [  0.   0.   0. ...   0.   0.   0.]
 [  0.   0.   0. ...   0.   0.   0.]]


In [27]:
!pip install Computer_Vision

In [2]:
!pip install computer-vision
